spring.application.name=library

#PORT
server.port=8080

#DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=123456a!@

#DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

#OTP
otp.expiry-seconds=

#JWT
jwt.signerKey=jOJi75vrVfRia2Mxvjp5vS2WwX3AhGbfWWxd9Doiubkt8J4Cba28JM/tSgl5b4N3V5W0I+hmQZwUhS+IAkm7Eg==
jwt.access-token-expiry=60
jwt.refresh-token-expiry=604800000

logging.level.org.springframework.security=DEBUG
