spring.application.name=library

#PORT
server.port=8080

#DATABASE
spring.datasource.url=jdbc:mysql://localhost:3306/library
spring.datasource.username=root
spring.datasource.password=123456a!@

#DRIVER
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#REDIS
spring.data.redis.host=localhost
spring.data.redis.port=6379

#OTP
otp.expiry-seconds=60

#JWT
jwt.access-signer-key=jOJi75vrVfRia2Mxvjp5vS2WwX3AhGbfWWxd9Doiubkt8J4Cba28JM/tSgl5b4N3V5W0I+hmQZwUhS+IAkm7Eg==
jwt.refresh-signer-key=3q6P4WQ8V9wq2mQxY4JgLxq5x5lD8d8W4mB8N6oM7nL2fS2eR7hJ1kP0vT9cA6gYwZb2QeN5rF1uI8xC3mL9dQ==
jwt.otp-signer-key=y7Xq2fL8vJm4RkN9aHpW3uTsBcZd6eFgQ1nKvMx5CiUr8YoEl0A=
jwt.access-token-expiry=900
jwt.refresh-token-expiry=2592000

#EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tranphuth0609@gmail.com
spring.mail.password=fsfjmtuitvbhhpuq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.security=DEBUG
