--create roles
CREATE TABLE ROLES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

--create permissions
CREATE TABLE PERMISSIONS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

--create roles_permissions
CREATE TABLE library.ROLES_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CONSTRAINT PK_ROLES_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

--create users_roles
CREATE TABLE library.USERS_ROLES (
    USER_ID VARCHAR(36) NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_USERS_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_RP_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT FK_RP_ROLE_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLES(id) ON DELETE CASCADE
);

--create users
CREATE TABLE library.USERS (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(500) NULL,
    PASSWORD VARCHAR(255) NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    MFA_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_LOGIN_AT DATETIME NULL,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_email (email),
);

--create accessToken
CREATE TABLE library.INVALIDATED_TOKEN (
    JTI      CHAR(36) PRIMARY KEY,
    EXPIRES_AT DATETIME NOT NULL
);

--create refreshToken
CREATE TABLE library.REFRESH_TOKEN (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    USER_ID VARCHAR(36) NOT NULL UNIQUE,
    EXPIRES_AT DATETIME(6) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_refresh_token_user FOREIGN KEY (USER_ID) REFERENCES users(id) ON DELETE CASCADE
);

--create auditLogs
CREATE TABLE library.AUDIT_LOGS (
    ID                          CHAR(36) PRIMARY KEY,
    TIMESTAMP                   DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    ACTOR_ID                    VARCHAR(64) NOT NULL,
    ACTOR_ROLE                 VARCHAR(64) NOT NULL,
    ACTOR_PERMISSIONS_SNAPSHOT  JSON NOT NULL,
    ACTION                      VARCHAR(64) NOT NULL,
    TARGET_TYPE                 VARCHAR(64) NOT NULL,
    TARGET_ID                   VARCHAR(64) NOT NULL,
    OLD_VALUE                   JSON NULL,
	NEW_VALUE                   JSON NULL,
    STATUS                      ENUM('SUCCESS', 'FAILED') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;