--create role
CREATE TABLE ROLES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

--create permission
CREATE TABLE PERMISSIONS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);
