--create roles
CREATE TABLE ROLES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    IS_SUPER BOOLEAN NOT NULL DEFAULT FALSE
);

--create permissions
CREATE TABLE PERMISSIONS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PUBLIC_ID VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    STATUS TINYINT DEFAULT 1,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

--create roles_permissions
CREATE TABLE library.ROLES_PERMISSIONS (
    ROLE_ID BIGINT NOT NULL,
    PERMISSION_ID BIGINT NOT NULL,
    CONSTRAINT PK_ROLES_PERMISSIONS PRIMARY KEY (ROLE_ID, PERMISSION_ID),
    CONSTRAINT FK_RP_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISSION FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS(ID) ON DELETE CASCADE
);

--create users_roles
CREATE TABLE library.USERS_ROLES (
    USER_ID VARCHAR(36) NOT NULL,
    ROLE_ID BIGINT NOT NULL,
    CONSTRAINT PK_USERS_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_RP_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS(id) ON DELETE CASCADE,
    CONSTRAINT FK_RP_ROLE_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLES(id) ON DELETE CASCADE
);

--create users
CREATE TABLE library.USERS (
    ID VARCHAR(36) NOT NULL DEFAULT (UUID()),
    CODE VARCHAR(100) NOT NULL UNIQUE,
    EMAIL VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    AVATAR_URL VARCHAR(500) NULL,
    PASSWORD VARCHAR(255) NULL,
    IS_ACTIVE BOOLEAN NOT NULL DEFAULT FALSE,
    IS_EMAIL_VERIFIED BOOLEAN NOT NULL DEFAULT FALSE,
    MFA_ENABLED BOOLEAN NOT NULL DEFAULT FALSE,
    IS_LOCKED BOOLEAN NOT NULL DEFAULT FALSE,
    FAILED_LOGIN_ATTEMPTS INT NOT NULL DEFAULT 0,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    LAST_LOGIN_AT DATETIME NULL,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    PRIMARY KEY (id),
    UNIQUE KEY uk_users_email (email),
);


