--create category
CREATE TABLE library.CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PARENT_ID BIGINT,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY(ID)
);

--create author
CREATE TABLE library.AUTHOR (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(100)  NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH DATE,
    DATE_OF_DEATH DATE,
    NATIONALITY VARCHAR(100),
    BIOGRAPHY TEXT,
    IMAGE_URL VARCHAR(500),
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

--create publisher
CREATE TABLE library.PUBLISHER (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    ADDRESS VARCHAR(500),
    PHONE VARCHAR(20),
    EMAIL VARCHAR(255),
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255)
);

CREATE TABLE library.CONFIGURATION (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    VALUE BIGINT NOT NULL,
    TYPE VARCHAR(100) NOT NULL,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CONSTRAINT UK_CONFIGURATION_TYPE_CODE UNIQUE (TYPE, CODE)
);

CREATE TABLE library.BOOK (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(20) NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION TEXT,
    PUBLISHER_ID BIGINT,
    CATEGORY_ID BIGINT,
    LANGUAGE VARCHAR(50),
    PUBLISHED_DATE DATE,
    PAGE_COUNT INT,
    COVER_IMAGE_URL VARCHAR(500),
    EDITION VARCHAR(100),
    TOTAL_COPIES INT NOT NULL DEFAULT 0,
    AVAILABLE_COPIES INT NOT NULL DEFAULT 0,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CONSTRAINT fk_books_publisher
        FOREIGN KEY (publisher_id) REFERENCES publishers(id),
    CONSTRAINT fk_books_category
        FOREIGN KEY (category_id) REFERENCES categories(id),
    CONSTRAINT chk_books_total_copies
        CHECK (total_copies >= 0),
    CONSTRAINT chk_books_available_copies
        CHECK (available_copies >= 0),
    CONSTRAINT chk_books_available_less_than_total
        CHECK (available_copies <= total_copies)
);