--create category
CREATE TABLE library.CATEGORY (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CODE VARCHAR(100) NOT NULL UNIQUE,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(1000),
    PARENT_ID BIGINT,
    IS_DELETED BOOLEAN NOT NULL DEFAULT FALSE,
    CREATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(255),
    UPDATED_BY VARCHAR(255),
    CONSTRAINT FK_CATEGORY_PARENT FOREIGN KEY (PARENT_ID) REFERENCES CATEGORY(ID)
);